[project]
name = "japanese-font-library-fonts"
version = "2.4.0"
description = "Project for developing Japanese fonts for Skyrim font mods."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fonttools>=4.61.1",
    "otf2ttf>=0.2",
    "skia-pathops>=0.9.1",
]

[tool.uv]
package = true

[project.scripts]
create_subset = "utils.subsetter.create_subset:main"
builder = "apps.skyrim.builder:main"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]